name: notify release
on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      manual_ios_version:
        description: 'Android Version (Only for testing)'
        required: false
jobs:
  notify_native_sdk_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        run: echo "Hello world!"