name: Update SDK Version on Dev Branch

on:
  create:

jobs:
  update-sdk-version:
    # dev-* 패턴의 브랜치가 생성될 때만 실행
    if: github.ref_type == 'branch' && startsWith(github.ref_name, 'dev-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from branch name
        id: version
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          VERSION=${BRANCH_NAME#dev-}
          echo "sdk_version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update SDK version in gradle.properties
        run: |
          sed -i -E "s/sdk_version=.*/sdk_version=${{ steps.version.outputs.sdk_version }}/" gradle.properties
          echo "Updated sdk_version to ${{ steps.version.outputs.sdk_version }}"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 변경사항이 있는지 확인
          if git diff --quiet gradle.properties; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add gradle.properties
          git commit -m "chore: update sdk_version to ${{ steps.version.outputs.sdk_version }}"
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
